// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vault.Infrastructure.Persistence;

#nullable disable

namespace Vault.Infrastructure.Migrations
{
    [DbContext(typeof(VaultDbContext))]
    partial class VaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vault.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("BannerImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("IconImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LinkShare")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("Collections", "Catalog");
                });

            modelBuilder.Entity("Vault.Domain.Entities.CollectionMember", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("TenantId", "CollectionId", "Email");

                    b.ToTable("CollectionMembers", "Catalog");
                });

            modelBuilder.Entity("Vault.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SortBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SortDirection")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("Target")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "CollectionId", "Id");

                    b.ToTable("Groups", "Catalog");
                });

            modelBuilder.Entity("Vault.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollectionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.PrimitiveCollection<string>("PhotoIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "CollectionId", "Id");

                    b.ToTable("Items", "Catalog");
                });

            modelBuilder.Entity("Vault.Domain.Entities.StoreListing", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.PrimitiveCollection<string>("Groups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("StoreListings", "Store");
                });

            modelBuilder.Entity("Vault.Domain.Entities.StoredImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("FocalX")
                        .HasColumnType("float");

                    b.Property<double?>("FocalY")
                        .HasColumnType("float");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UnreferencedSinceUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Images", "Storage");
                });

            modelBuilder.Entity("Vault.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("DefaultTheme")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", "Identity");
                });

            modelBuilder.Entity("Vault.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", "Identity");
                });

            modelBuilder.Entity("Vault.Domain.Entities.Collection", b =>
                {
                    b.HasOne("Vault.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vault.Domain.Entities.CollectionMember", b =>
                {
                    b.HasOne("Vault.Domain.Entities.Collection", null)
                        .WithMany("Members")
                        .HasForeignKey("TenantId", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vault.Domain.Entities.Group", b =>
                {
                    b.HasOne("Vault.Domain.Entities.Collection", null)
                        .WithMany("Groups")
                        .HasForeignKey("TenantId", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Vault.Domain.ValueObjects.GroupField", "Fields", b1 =>
                        {
                            b1.Property<Guid>("GroupTenantId");

                            b1.Property<string>("GroupCollectionId");

                            b1.Property<string>("GroupId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("Name");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasJsonPropertyName("Type");

                            b1.HasKey("GroupTenantId", "GroupCollectionId", "GroupId", "__synthesizedOrdinal");

                            b1.ToTable("Groups", "Catalog");

                            b1
                                .ToJson("Fields")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("GroupTenantId", "GroupCollectionId", "GroupId");
                        });

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Vault.Domain.Entities.Item", b =>
                {
                    b.HasOne("Vault.Domain.Entities.Collection", null)
                        .WithMany("Items")
                        .HasForeignKey("TenantId", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Vault.Domain.ValueObjects.CustomFieldValue", "Custom", b1 =>
                        {
                            b1.Property<Guid>("ItemTenantId");

                            b1.Property<string>("ItemCollectionId");

                            b1.Property<string>("ItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Key")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ItemTenantId", "ItemCollectionId", "ItemId", "__synthesizedOrdinal");

                            b1.ToTable("Items", "Catalog");

                            b1
                                .ToJson("Custom")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ItemTenantId", "ItemCollectionId", "ItemId");
                        });

                    b.OwnsMany("Vault.Domain.ValueObjects.ItemCopy", "Copies", b1 =>
                        {
                            b1.Property<Guid>("ItemTenantId");

                            b1.Property<string>("ItemCollectionId");

                            b1.Property<string>("ItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<DateOnly?>("AcquiredOn")
                                .HasJsonPropertyName("AcquiredOn");

                            b1.Property<string>("Condition")
                                .IsRequired()
                                .HasJsonPropertyName("Condition");

                            b1.Property<string>("Id")
                                .HasJsonPropertyName("Id");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasJsonPropertyName("Notes");

                            b1.Property<decimal>("Price")
                                .HasPrecision(12, 2)
                                .HasJsonPropertyName("Price");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasJsonPropertyName("Status");

                            b1.Property<decimal?>("Value")
                                .HasPrecision(12, 2)
                                .HasJsonPropertyName("Value");

                            b1.HasKey("ItemTenantId", "ItemCollectionId", "ItemId", "__synthesizedOrdinal");

                            b1.ToTable("Items", "Catalog");

                            b1
                                .ToJson("Copies")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ItemTenantId", "ItemCollectionId", "ItemId");
                        });

                    b.Navigation("Copies");

                    b.Navigation("Custom");
                });

            modelBuilder.Entity("Vault.Domain.Entities.StoreListing", b =>
                {
                    b.OwnsMany("Vault.Domain.ValueObjects.StoreListingItem", "Items", b1 =>
                        {
                            b1.Property<string>("StoreListingId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Group")
                                .IsRequired();

                            b1.Property<string>("Id");

                            b1.Property<string>("Img")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<decimal>("Value");

                            b1.Property<int>("Year");

                            b1.HasKey("StoreListingId", "__synthesizedOrdinal");

                            b1.ToTable("StoreListings", "Store");

                            b1
                                .ToJson("Items")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("StoreListingId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Vault.Domain.Entities.StoredImage", b =>
                {
                    b.HasOne("Vault.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vault.Domain.Entities.User", b =>
                {
                    b.HasOne("Vault.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vault.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Items");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
